# Generated by Django 5.2.8 on 2025-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=75)),
                ('weakness', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('set', models.CharField(max_length=200)),
                ('health', models.IntegerField()),
            ],
        ),
    ]
