# Generated by Django 5.2.8 on 2025-11-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='titel',
            new_name='title',
        ),
    ]
